### ISSUE TITLE
Error in seeding the data

### ISSUE THREAD

**Issue by gurshaan17** [JS-Hub-ZW/hackathon-backend#27]
`const User = require('../schemas/users')
const Event = require('../schemas/events')

const events = require("../../data/events")

async function seedDB(){
await User.deleteMany({})
const insertedUsers = await User.insertMany([
    {name: 'John', surname: 'Doe', email: 'j@doe.com', password: '1234'  },
    { name: 'Mary', surname: 'Doe', email: 'm@doe.com', password: '1234' },
    { name: 'Jane', surname: 'Doe', email: 'jn@doe.com', password: '1234'  },
    { name: 'James', surname: 'Doe', email: 'jm@doe.com', password: '1234'  },
    { name: 'Rene', surname: 'Doe', email: 'r@doe.com', password: '1234'  }
    ])
    console.log('Starting with new data in the database...')
}

**const insertedEvents = await Event.insertMany([
    ...events
])**

module.exports = seedDB`

here  await is outside the async function. This is causing errors put that part inside the main async function

In the user schema for the database, name field is not required always but the username field is always required to be present.
Key can be corrected here  {name: 'John', surname: 'Doe', email: 'j@doe.com', password: '1234'  } or another field username could be added

@takumade

**Comment by takumade** [comment]
Thank you @gurshaan17 for the great observation, do you  want to solve it, so I can assign you

**Comment by gurshaan17** [comment]
Yes, I can solve it.
